const DL_API_PREFIX_KEY = 'dlapi_';
const BASIC_TAG = 'div';
const DLAPI_CHECK_DELAY = 20;
const THEME_KEY = `${DL_API_PREFIX_KEY}THEME_DATA`;

export { BASIC_TAG, DLAPI_CHECK_DELAY, THEME_KEY, DL_API_PREFIX_KEY };
