const MAIN_PAGE = 'MAIN_PAGE';
const PRODUCT_PAGE = 'PRODUCT_PAGE';
const CATEGORY_PAGE = 'CATEGORY_PAGE';

const MAIN_PAGE_SELECTOR = '.home';
const PRODUCT_PAGE_SELECTOR = '.single-product';
const CATEGORY_PAGE_SELECTOR = '.tax-product_cat';

export {
  MAIN_PAGE,
  PRODUCT_PAGE,
  CATEGORY_PAGE,
  MAIN_PAGE_SELECTOR,
  PRODUCT_PAGE_SELECTOR,
  CATEGORY_PAGE_SELECTOR,
};
