import { DL_API_PREFIX_KEY } from 'consts/common';

const ONET_PRODUCT_CLASS = 'onet-product';
const SPONSORED_PRODUCT_TAG = 'onet-product-';
const TAG_REPLACEMENT_KEY = '%TAG_LABEL%';
const DSA_ICON_CLASS = 'onet-dsa-icon-link';
const HTML_DATA_CATEGORY_KEY = `${DL_API_PREFIX_KEY}HTML_DATA_CATEGORY`;
const HTML_DATA_MAIN_KEY = `${DL_API_PREFIX_KEY}HTML_DATA_MAIN`;
const HTML_DATA_PRODUCT_KEY = `${DL_API_PREFIX_KEY}HTML_DATA_PRODUCT`;
const TAG_LABEL_HOOK_CLASS = 'hook-label';

export {
  ONET_PRODUCT_CLASS,
  SPONSORED_PRODUCT_TAG,
  TAG_REPLACEMENT_KEY,
  DSA_ICON_CLASS,
  HTML_DATA_CATEGORY_KEY,
  HTML_DATA_MAIN_KEY,
  HTML_DATA_PRODUCT_KEY,
  TAG_LABEL_HOOK_CLASS,
};
